services:
  lottery_api_server:
    image: jh8459/lottery_api_server:latest
    container_name: lottery_api_server
    ports:
      - '${API_SERVER_PORT}:${API_SERVER_PORT}'
    volumes:
      - ./api/logs:/api/logs
      - ./api/public:/api/public
      - ./api/resource:/api/resource
    env_file:
      - ./api/.env
    environment:
      API_NODE_ENV: prod
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${API_SERVER_PORT}/health']
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - lottery_net

  lottery_crawler_server:
    image: jh8459/lottery_crawler_server:latest
    container_name: lottery_crawler_server
    ports:
      - '${CRAWLER_SERVER_PORT}:${CRAWLER_SERVER_PORT}'
    volumes:
      - ./crawler/logs:/crawler/logs
      - ./crawler/public:/crawler/public
      - ./crawler/resource:/crawler/resource
    env_file:
      - ./crawler/.env
    environment:
      - TZ=Asia/Seoul
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${CRAWLER_SERVER_PORT}/health']
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - lottery_net

  lottery_redis:
    image: redis:latest
    container_name: lottery_redis
    restart: always
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1h
      timeout: 30s
      retries: 3
      start_period: 30s
    networks:
      - lottery_net

  lottery_website:
    image: jh8459/lottery_website:latest
    container_name: lottery_website
    ports:
      - '${WEBSITE_PORT}:${WEBSITE_PORT}'
    restart: always
    networks:
      - lottery_net

networks:
  lottery_net:
    driver: bridge
