services:
  lottery_test_db:
    image: mariadb:latest
    container_name: lottery_test_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: lottery_test_db
      MYSQL_PASSWORD: 1234
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password

  lottery_test_redis:
    image: redis:latest
    container_name: lottery_test_redis
    ports:
      - 6380:6379
