name: Deploy to NAS (CD)

on:
  workflow_run:
    workflows: ['E2E Test & Build Docker Images (CI)']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to NAS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to NAS via SSH - Test Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: echo "✅ NAS 접속 성공"

      - name: Update Git Repository on NAS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            cd /volume1/docker/lottery
            echo "🌀 GitHub master 브랜치 최신화"
            git fetch origin
            git reset --hard origin/master

      - name: Create .env files on NAS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            cd /volume1/docker/lottery
            echo "📦 .env 파일 생성 시작"

            # 공통 .env
            mkdir -p ./api ./crawler
            rm -f .env ./api/.env ./crawler/.env

            cat <<EOF > .env
            API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}
            CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}
            WEBSITE_PORT=${{ secrets.WEBSITE_PORT }}
            EOF

            cat <<EOF > ./api/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}
            API_EMAIL_USERNAME=${{ secrets.API_EMAIL_USERNAME }}
            API_EMAIL_PASSWORD=${{ secrets.API_EMAIL_PASSWORD }}
            API_EMAIL_HOST=${{ secrets.API_EMAIL_HOST }}
            API_EMAIL_PORT=${{ secrets.API_EMAIL_PORT }}
            API_EMAIL_FROM=${{ secrets.API_EMAIL_FROM }}
            API_REDIS_HOST=${{ secrets.API_REDIS_HOST }}
            API_REDIS_PORT=${{ secrets.API_REDIS_PORT }}
            API_SLACK_SIGNING_SECRET=${{ secrets.API_SLACK_SIGNING_SECRET }}
            API_SLACK_BOT_TOKEN=${{ secrets.API_SLACK_BOT_TOKEN }}
            API_SLACK_CLIENT_ID=${{ secrets.API_SLACK_CLIENT_ID }}
            API_SLACK_CLIENT_SECRET=${{ secrets.API_SLACK_CLIENT_SECRET }}
            API_SLACK_WEBHOOK_URL=${{ secrets.API_SLACK_WEBHOOK_URL }}
            COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}
            SWAGGER_USERNAME=${{ secrets.SWAGGER_USERNAME }}
            SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }}
            EOF

            cat <<EOF > ./crawler/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}
            COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}
            EOF

            echo "✅ .env 파일 생성 완료"

      - name: Docker Pull, Down, Up on NAS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            cd /volume1/docker/lottery

            echo "🐳 최신 Docker 이미지 Pull"
            /usr/local/bin/docker-compose pull

            echo "🧨 기존 컨테이너 중지 및 삭제"
            /usr/local/bin/docker-compose down

            echo "🚀 새 컨테이너 실행"
            /usr/local/bin/docker-compose up -d

            echo "🎉 배포 완료"
