name: Deploy to NAS (CD)

on:
  pull_request:
    branches: [prod]

jobs:
  deploy:
    name: Deploy to NAS
    runs-on: ubuntu-latest

    steps:
      - name: Connect to NAS via SSH and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_PASSWORD }}
          port: ${{ secrets.NAS_PORT }}
          script: |
            echo "✅ NAS 접속 성공"

            cd /volume1/docker/lottery

            echo "📦 COMMON .env 생성"
            [ -f .env ] && rm .env
            cat <<EOF > .env
            NODE_ENV=${{ secrets.NODE_ENV }}
            API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}
            CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}
            WEBSITE_PORT=${{ secrets.WEBSITE_PORT }}
            EOF

            echo "📦 API .env 생성"
            mkdir -p ./api
            [ -f ./api/.env ] && rm ./api/.env
            cat <<EOF > ./api/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            API_NODE_ENV=${{ secrets.API_NODE_ENV }}
            API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}
            API_EMAIL_USERNAME=${{ secrets.API_EMAIL_USERNAME }}
            API_EMAIL_PASSWORD=${{ secrets.API_EMAIL_PASSWORD }}
            API_EMAIL_HOST=${{ secrets.API_EMAIL_HOST }}
            API_EMAIL_PORT=${{ secrets.API_EMAIL_PORT }}
            API_EMAIL_FROM=${{ secrets.API_EMAIL_FROM }}
            API_REDIS_HOST=${{ secrets.API_REDIS_HOST }}
            API_REDIS_PORT=${{ secrets.API_REDIS_PORT }}
            API_SLACK_SIGNING_SECRET=${{ secrets.API_SLACK_SIGNING_SECRET }}
            API_SLACK_BOT_TOKEN=${{ secrets.API_SLACK_BOT_TOKEN }}
            API_SLACK_CLIENT_ID=${{ secrets.API_SLACK_CLIENT_ID }}
            API_SLACK_CLIENT_SECRET=${{ secrets.API_SLACK_CLIENT_SECRET }}
            COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}
            SWAGGER_USERNAME=${{ secrets.SWAGGER_USERNAME }}
            SWAGGER_PASSWORD=${{ secrets.SWAGGER_PASSWORD }}
            EOF

            echo "📦 CRAWLER .env 생성"
            mkdir -p ./crawler
            [ -f ./crawler/.env ] && rm ./crawler/.env
            cat <<EOF > ./crawler/.env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_DATABASE=${{ secrets.DB_DATABASE }}
            CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}
            COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}
            EOF

            echo "🌀 GitHub prod 브랜치 코드 최신화"
            git fetch origin
            git reset --hard origin/prod

            echo "🐳 Docker 이미지 Pull"
            /usr/local/bin/docker-compose pull

            echo "🧨 기존 컨테이너 중지"
            /usr/local/bin/docker-compose down

            echo "🚀 최신 이미지로 컨테이너 재시작"
            /usr/local/bin/docker-compose up -d

            echo "✅ 배포 완료 🎉"
