name: Build & Push Docker Images (CI)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build and push API
      - name: Build and Push lottery_api_server Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lottery_api_server:latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lottery_api_server:latest

      # Build and push Crawler
      - name: Build and Push lottery_crawler_server Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lottery_crawler_server:latest ./crawler
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lottery_crawler_server:latest

      # Build and push Website
      - name: Build and Push lottery_website Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lottery_website:latest ./website
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/lottery_website:latest

      # Github Pull Request to prod branch
      - name: Create Pull Request to prod branch
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.COMMON_GITHUB_TOKEN }}
          title: 'Merge master into prod'
          commit-message: 'ci: sync master to prod'
          base: prod
          branch: master
          body: |
            이 PR은 master 브랜치에서 prod 브랜치로의 자동 PR입니다.
            빌드 및 Docker Hub 푸시가 완료된 후 생성되었습니다.
