name: master branch CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  EC2:
    name: CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "/"

    steps:
      - name: Remote SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            echo "############# START #############"
            cd /home/ubuntu/LOTTERY
            echo "############# GIT PULL #############"
            git pull origin master

            echo "############# CREATE CRAWLER .ENV #############"
            cd /home/ubuntu/LOTTERY/crawler
            touch .env
            echo "SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}" >> .env
            cat .env
            echo "############# DOCKER SCRIPT #############"
            cd /home/ubuntu/LOTTERY
            sh script.sh
