name: master branch CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  EC2:
    name: CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '/'

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Remote SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            echo "############# START #############"
            cd /home/ubuntu/LOTTERY
            echo "############# GIT PULL #############"
            sudo git pull origin master

            echo "############# CREATE CRAWLER .ENV #############"
            cd /home/ubuntu/LOTTERY/crawler
            [ -f .env ] && rm .env
            touch .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}" >> .env
            echo "COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}" >> .env
            cat .env

            echo "############# CREATE API .ENV #############"
            cd /home/ubuntu/LOTTERY/api
            [ -f .env ] && rm .env
            touch .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "API_NODE_ENV=${{ secrets.API_NODE_ENV }}" >> .env
            echo "API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}" >> .env
            echo "API_EMAIL_USERNAME=${{ secrets.API_EMAIL_USERNAME }}" >> .env
            echo "API_EMAIL_PASSWORD=${{ secrets.API_EMAIL_PASSWORD }}" >> .env
            echo "API_EMAIL_HOST=${{ secrets.API_EMAIL_HOST }}" >> .env
            echo "API_EMAIL_PORT=${{ secrets.API_EMAIL_PORT }}" >> .env
            echo "API_EMAIL_FROM=${{ secrets.API_EMAIL_FROM }}" >> .env
            echo "API_REDIS_HOST=${{ secrets.API_REDIS_HOST }}" >> .env
            echo "API_REDIS_PORT=${{ secrets.API_REDIS_PORT }}" >> .env
            echo "COMMON_GITHUB_TOKEN=${{ secrets.COMMON_GITHUB_TOKEN }}" >> .env
            cat .env

            echo "############# DOCKER BUILD SCRIPT #############"
            cd /home/ubuntu/LOTTERY
            sh build.script.sh

            echo "############# DOCKER DEPLOY SCRIPT #############"
            cd /home/ubuntu/LOTTERY
            sh deploy.script.sh
