name: master branch CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  EC2:
    name: CI/CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '/'

    steps:
      - name: Remote SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SECRET_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            echo "############# START #############"
            cd /home/ubuntu/LOTTERY
            echo "############# GIT PULL #############"
            git pull origin master

            echo "############# CREATE CRAWLER .ENV #############"
            cd /home/ubuntu/LOTTERY/crawler
            [ -f .env ] && rm .env
            touch .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "CRAWLER_SERVER_PORT=${{ secrets.CRAWLER_SERVER_PORT }}" >> .env
            cat .env

            echo "############# CREATE API .ENV #############"
            cd /home/ubuntu/LOTTERY/api
            [ -f .env ] && rm .env
            touch .env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
            echo "API_NODE_ENV=${{ secrets.API_NODE_ENV }}" >> .env
            echo "API_SERVER_PORT=${{ secrets.API_SERVER_PORT }}" >> .env
            cat .env

            echo "############# DOCKER SCRIPT #############"
            cd /home/ubuntu/LOTTERY
            sh script.sh
